package siustis.teodor;
import java.io.IOException;
import java.io.InputStream;
import java.text.BreakIterator;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.StringTokenizer;
import java.util.logging.Logger;

import org.apache.commons.lang3.StringUtils;
import org.apache.tika.Tika;
import org.apache.tika.exception.TikaException;

import com.google.common.collect.HashBasedTable;
import com.google.common.collect.Multiset.Entry;



import com.google.common.collect.Table;
public class MyTable {
	//Guava table
	static Table<String,String,String> ICD10 = HashBasedTable.create();
	Table<String,String,String> result = HashBasedTable.create();
	Table<String,String,String> diseases = HashBasedTable.create();
	public MyTable(){

	
ICD10.put("Cholera","Certain infectious and parasitic diseases","A00");

ICD10.put("Cholera","Certain infectious and parasitic diseases", "A00");
ICD10.put("Typhoid fever","Certain infectious and parasitic diseases", "A01.0");
ICD10.put("Paratyphoid fever A","Certain infectious and parasitic diseases", "A01.1");
ICD10.put("Paratyphoid fever B","Certain infectious and parasitic diseases", "A01.2");
ICD10.put("Paratyhpoid fever C","Certain infectious and parasitic diseases", "A01.3");
ICD10.put("Salmonella enteritis","Certain infectious and parasitic diseases", "A02.0");
ICD10.put("Salmonella sepsis","Certain infectious and parasitic diseases", "A02.1");
ICD10.put("Salmonella sepsis","Certain infectious and parasitic diseases", "A03");
ICD10.put("Escherichia coli","Certain infectious and parasitic diseases", "A04");
ICD10.put("Foodborne staphylococcal intoxication","Certain infectious and parasitic diseases", "A05");
ICD10.put("Botulism","Certain infectious and parasitic diseases", "A05.1");
ICD10.put("Amoebiasis","Certain infectious and parasitic diseases", "A06");
ICD10.put("Balantidiasis","Certain infectious and parasitic diseases", "A07.0");
ICD10.put("Giardiasis","Certain infectious and parasitic diseases", "A07.1");
ICD10.put("Cryptosporidiosis","Certain infectious and parasitic diseases", "A07.2");
ICD10.put("Isosporiasis","Certain infectious and parasitic diseases", "A07.3");
ICD10.put("Rotaviral enteritis","Certain infectious and parasitic diseases", "A08.0");
ICD10.put("Acute gastroenteropathy","Certain infectious and parasitic diseases", "A08.1");
ICD10.put("Adenoviral enteritis","Certain infectious and parasitic diseases", "A08.2");
ICD10.put("Viral enteritis","Certain infectious and parasitic diseases", "A08.3");
ICD10.put("Viral intestinal infection","Certain infectious and parasitic diseases", "A08.4");
ICD10.put("Gastroenteritis of unspecified origin","Certain infectious and parasitic diseases", "A09");
ICD10.put("Respiratory turbeculosis, bacteriologically and histologically confirmed","Certain infectious and parasitic diseases", "A15");
ICD10.put("Respiratory tuberculosis, not confirmed bacteriologically or histologically","Certain infectious and parasitic diseases", "A16");
ICD10.put("Tuberculosis meningitis","Certain infectious and parasitic diseases", "A17.0");
ICD10.put("Meningeal tuberculoma","Certain infectious and parasitic diseases", "A17.1");
ICD10.put("Other tuberculosis of nervous system","Certain infectious and parasitic diseases", "A17.2");
ICD10.put("Tuberculosis of bones and joints","Certain infectious and parasitic diseases", "A18.0");
ICD10.put("Tuberculosis of genitourinary system","Certain infectious and parasitic diseases", "A18.1");
ICD10.put("Tuberculosis of peripheral lymphadenopathy","Certain infectious and parasitic diseases", "A18.2");
ICD10.put("Tuberculosis of intestines","Certain infectious and parasitic diseases", "A18.3");
ICD10.put("Tuberculosis of skin","Certain infectious and parasitic diseases", "A18.4");
ICD10.put("Tuberculosis of eye","Certain infectious and parasitic diseases", "A18.5");
ICD10.put("Tuberculosis of ear","Certain infectious and parasitic diseases", "A18.6");
ICD10.put("Tuberculosis of adrenal glands","Certain infectious and parasitic diseases", "A18.7");
ICD10.put("Tuberculosis of other specified organs","Certain infectious and parasitic diseases", "A18.8");
ICD10.put("Acute miliary tuberculosis of a single specified site","Certain infectious and parasitic diseases", "A19.0");
ICD10.put("Acute miliary tuberculosis of multiple sites","Certain infectious and parasitic diseases", "A19.1");
ICD10.put("Acute miliary tuberculosis,unspecified","Certain infectious and parasitic diseases", "A19.2");
ICD10.put("Other miliary tuberculosis","Certain infectious and parasitic diseases", "A19.3");
ICD10.put("Bubonic plague","Certain infectious and parasitic diseases", "A20.0");
ICD10.put("Cellulocutaneous plague","Certain infectious and parasitic diseases", "A20.1");
ICD10.put("Pneumonic plague","Certain infectious and parasitic diseases", "A20.2");
ICD10.put("Plague meningitis","Certain infectious and parasitic diseases", "A20.3");
ICD10.put("Septicaemic plague","Certain infectious and parasitic diseases", "A20.4");
ICD10.put("Other form of plague","Certain infectious and parasitic diseases", "A20.5");
ICD10.put("Ulceroglandular tularaemia","Certain infectious and parasitic diseases", "A21.0");
ICD10.put("culoglandular tularaemia","Certain infectious and parasitic diseases", "A21.1O");
ICD10.put("Pulmonary tularaemia","Certain infectious and parasitic diseases", "A21.2");
ICD10.put("Gastrointestinal tularaemia","Certain infectious and parasitic diseases", "A21.3");
ICD10.put("Generalized tularaemia","Certain infectious and parasitic diseases", "A21.7");
ICD10.put("Anthrax","Certain infectious and parasitic diseases", "A22");
ICD10.put("Brucellosis","Certain infectious and parasitic diseases","A23");
ICD10.put("Glanders","Certain infectious and parasitic diseases", "A24.0");
ICD10.put("Acute and fulminating meliodosis","Certain infectious and parasitic diseases", "A24.1");
ICD10.put("Subacute and chronic meliodosis","Certain infectious and parasitic diseases", "A24.2");
ICD10.put("Spirillosis","Certain infectious and parasitic diseases", "A25.0");
ICD10.put("Streptobacillosis","Certain infectious and parasitic diseases", "A25.1");
ICD10.put("Erysipeloid","Certain infectious and parasitic diseases", "A26");
ICD10.put("Leptospirosis","Certain infectious and parasitic diseases", "A27");
ICD10.put("Leprosy","Certain infectious and parasitic diseases", "A30");
ICD10.put("Pulmonary mycobacterial infection","Certain infectious and parasitic diseases", "A31.0");
ICD10.put("Cutaneous mycobacterial infection","Certain infectious and parasitic diseases", "A31.1");
ICD10.put("Other mycobacterial infection","Certain infectious and parasitic diseases", "A31.2");
ICD10.put("Cutaneous listeriosis","Certain infectious and parasitic diseases", "A32.0");
ICD10.put("Listerial meningitis","Certain infectious and parasitic diseases", "A32.1");
ICD10.put("Listerial sepsis","Certain infectious and parasitic diseases", "A32.7");
ICD10.put("Tetanus neonatorum","Certain infectious and parasitic diseases", "A33");
ICD10.put("Obstetrical tetanus","Certain infectious and parasitic diseases", "A34");
ICD10.put("Other tetanus","Certain infectious and parasitic diseases", "A35");
ICD10.put("Diphtheria","Certain infectious and parasitic diseases", "A36");
ICD10.put("Whooping cough","Certain infectious and parasitic diseases", "A37");
ICD10.put("Scarlet fever","Certain infectious and parasitic diseases", "A38");
ICD10.put("Meningococcal infection","Certain infectious and parasitic diseases", "A39");
ICD10.put("Streptococcal sepsis","Certain infectious and parasitic diseases", "A40");
ICD10.put("Other sepsis","Certain infectious and parasitic diseases", "A41");
ICD10.put("Actinomycosis","Certain infectious and parasitic diseases", "A42");
ICD10.put("Pulmonary actinomycosis","Certain infectious and parasitic diseases", "A42.0");
ICD10.put("Abdominal actinomycosis","Certain infectious and parasitic diseases", "A42.1");
ICD10.put("Cervicofacial actinomycosis","Certain infectious and parasitic diseases", "A42.2");
ICD10.put("Actinomycotic sepsis","Certain infectious and parasitic diseases", "A42.7");
ICD10.put("Pulmonary nocardiosis","Certain infectious and parasitic diseases", "A43.0");
ICD10.put("Cutaneous nocardiosis","Certain infectious and parasitic diseases", "A43.1");
ICD10.put("Other forms of nocardiosis","Certain infectious and parasitic diseases", "A43.8");
ICD10.put("Bartonollosis","Certain infectious and parasitic diseases", "A44");
ICD10.put("Erysipelas","Certain infectious and parasitic diseases", "A46");
ICD10.put("Gas gangrene","Certain infectious and parasitic diseases", "A48.0");
ICD10.put("Legionnaires disease","Certain infectious and parasitic diseases", "A48.1");
ICD10.put("Pontiac fever","Certain infectious and parasitic diseases", "A48.2");
ICD10.put("Toxic shock syndrome","Certain infectious and parasitic diseases", "A48.3");
ICD10.put("Toxic shock syndrome","Certain infectious and parasitic diseases", "A48.4");
ICD10.put("Congenital syphilis","Certain infectious and parasitic diseases", "A50");
ICD10.put("Early syphilis","Certain infectious and parasitic diseases", "A51");
ICD10.put("Late syphilis","Certain infectious and parasitic diseases", "A52");
ICD10.put("Gonoccoccal infection","Certain infectious and parasitic diseases", "A54");
ICD10.put("Chancroid","Certain infectious and parasitic diseases", "A57");
ICD10.put("Granuloma inguinale","Certain infectious and parasitic diseases", "A58");
ICD10.put("Nonvenereal syphilis","Certain infectious and parasitic diseases", "A65");
ICD10.put("Yaws","Certain infectious and parasitic diseases", "A66");
ICD10.put("Pinta","Certain infectious and parasitic diseases", "A67");
ICD10.put("Relapsing fever","Certain infectious and parasitic diseases", "A68");
ICD10.put("Chlamydia psittaci infection","Certain infectious and parasitic diseases", "A70");
ICD10.put("Trachoma","Certain infectious and parasitic diseases", "A71");
ICD10.put("Typhus fever","Certain infectious and parasitic diseases", "A75");
ICD10.put("Spotted fever","Certain infectious and parasitic diseases", "A77");
ICD10.put("Q fever","Certain infectious and parasitic diseases", "A78");
ICD10.put("Acute poliomyelitis","Certain infectious and parasitic diseases", "A80");
ICD10.put("Creutzfeldt-Jakob disease","Certain infectious and parasitic diseases", "A81.0");
ICD10.put("Subacute sclerosing panencephalitis","Certain infectious and parasitic diseases", "A81.1");
ICD10.put("Progrssive multifocal leukoencephalopathy","Certain infectious and parasitic diseases", "A81.2");
ICD10.put("Rabies","Certain infectious and parasitic diseases", "A82");
ICD10.put("Japanese encephalitis","Certain infectious and parasitic diseases", "A83.0");
ICD10.put("Western equine encephalitis","Certain infectious and parasitic diseases", "A83.1");
ICD10.put("Eastern equine encephalitis","Certain infectious and parasitic diseases", "A83.2");
ICD10.put("St Louis encephalitis","Certain infectious and parasitic diseases", "A83.3");
ICD10.put("Australian encephalitis","Certain infectious and parasitic diseases", "A83.4");
ICD10.put("California encephalitis","Certain infectious and parasitic diseases", "A83.5");
ICD10.put("Rocio virus disease","Certain infectious and parasitic diseases", "A83.6");
ICD10.put("Tick-borne viral encephalitis","Certain infectious and parasitic diseases", "A84");
ICD10.put("Enteroviral encephalitis","Certain infectious and parasitic diseases", "A85.0");
ICD10.put("Adenoviral encephalitis","Certain infectious and parasitic diseases", "A85.1");
ICD10.put("Arthropod-borne viral encephalitis","Certain infectious and parasitic diseases", "A85.2");
ICD10.put("Unspecified viral encephalitis","Certain infectious and parasitic diseases", "A86");
ICD10.put("Enteroviral meningitis","Certain infectious and parasitic diseases", "A87.0");
ICD10.put("Adenoviral meningitis","Certain infectious and parasitic diseases", "A87.1");
ICD10.put("Lymphocytic choriomeningitis","Certain infectious and parasitic diseases", "A87.2");
ICD10.put("Chikungunya virus disease","Certain infectious and parasitic diseases", "A92.0");
ICD10.put("O'nyong-nyong fever","Certain infectious and parasitic diseases", "A92.1");
ICD10.put("Venezuelan equine fever","Certain infectious and parasitic diseases", "A92.2");
ICD10.put("West Nile virus infection","Certain infectious and parasitic diseases", "A92.3");
ICD10.put("Rift Valley fever","Certain infectious and parasitic diseases", "A92.4");
ICD10.put("Oropouche virus disease","Certain infectious and parasitic diseases", "A93.0");
ICD10.put("Sandfly fever","Certain infectious and parasitic diseases", "A93.1");
ICD10.put("Colorado tick fever","Certain infectious and parasitic diseases", "A93.2");
ICD10.put("Yellow fever","Certain infectious and parasitic diseases", "A95");
ICD10.put("Junin haemoragic fever","Certain infectious and parasitic diseases", "A96.0");
ICD10.put("Machupo haemorrhagic fever","Certain infectious and parasitic diseases", "A96.1");
ICD10.put("Lassa fever","Certain infectious and parasitic diseases", "A96.2");
ICD10.put("Dengue","Certain infectious and parasitic diseases", "A97");
ICD10.put("Crimean-Congo haemorrhagic fever","Certain infectious and parasitic diseases", "A98.0");
ICD10.put("Omsk haemorrhagic fever","Certain infectious and parasitic diseases", "A98.1");
ICD10.put("Kyasanur Forset disease","Certain infectious and parasitic diseases", "A98.2");
ICD10.put("Marburg virus disease","Certain infectious and parasitic diseases", "A98.3");
ICD10.put("Ebola virus disease","Certain infectious and parasitic diseases", "A98.4");
ICD10.put("Eczema herpeticum","Certain infectious and parasitic diseases","B00.0");
ICD10.put("Herpesviral vesicular dermatitis","Certain infectious and parasitic diseases","B00.1");
ICD10.put("Herpesviral gingivostomatitis and pharyngotonsilitis","Certain infectious and parasitic diseases","B00.2");
ICD10.put("Herpesviral meningitis","Certain infectious and parasitic diseases","B00.3");
ICD10.put("Herpesviral encephalitis ","Certain infectious and parasitic diseases","B00.4");
ICD10.put("Herpesviral ocular disease","Certain infectious and parasitic diseases","B00.5");
ICD10.put("Varicella meningitis","Certain infectious and parasitic diseases","B01.0");
ICD10.put("Varicella encephalitis","Certain infectious and parasitic diseases","B01.1");
ICD10.put("Varicella pneumonia","Certain infectious and parasitic diseases","B01.2");
ICD10.put("Zoster","Certain infectious and parasitic diseases","B02");
ICD10.put("Smallpox","Certain infectious and parasitic diseases","B03");
ICD10.put("Monkeypox","Certain infectious and parasitic diseases","B04");
ICD10.put("Measles","Certain infectious and parasitic diseases","B05");
ICD10.put("Rubella","Certain infectious and parasitic diseases","B06");
ICD10.put("Viral warts","Certain infectious and parasitic diseases","B07");
ICD10.put("Acute hepatitis A","Certain infectious and parasitic diseases","B15");
ICD10.put("Acute hepatitis B","Certain infectious and parasitic diseases","B16");
ICD10.put("Acute delta-(super)infeciton of hepatitis B carrier","Certain infectious and parasitic diseases","B17.0");
ICD10.put("Acute hepatitis C","Certain infectious and parasitic diseases","B17.1");
ICD10.put("Acute hepatitis E","Certain infectious and parasitic diseases","B17.2");
ICD10.put("Chronic viral hepatitis","Certain infectious and parasitic diseases","B18");
ICD10.put("HIV disease resulting in infectious and parasitic disease","Certain infectious and parasitic diseases","B19");
ICD10.put("HIV disease resulting in malignant neoplasm","Certain infectious and parasitic diseases","B20");
ICD10.put("HIV resulting in other specified diseases","Certain infectious and parasitic diseases","B21");
ICD10.put("Cytomegaloviral hepatitis","Certain infectious and parasitic diseases","B25.1");
ICD10.put("Cytomegaloviral pancreatitis","Certain infectious and parasitic diseases","B25.2");
ICD10.put("Mumps","Certain infectious and parasitic diseases","B26");
ICD10.put("Gammaherpesviral mononucelosis","Certain infectious and parasitic diseases","B27.0");
ICD10.put("Cytomegaloviral pneumonitis","Certain infectious and parasitic diseases","B25.0");
ICD10.put("Cytomegaloviral mononucelosis","Certain infectious and parasitic diseases","B26");
ICD10.put("Viral conjunctivitis","Certain infectious and parasitic diseases","B30");
ICD10.put("Dermatophytosis","Certain infectious and parasitic diseases","B35");
ICD10.put("Pityriasis versicolor","Certain infectious and parasitic diseases","B36.0");
ICD10.put("Tinea nigra","Certain infectious and parasitic diseases","B36.1");
ICD10.put("White piedra","Certain infectious and parasitic diseases","B36.2");
ICD10.put("Black piedra","Certain infectious and parasitic diseases","B36.3");
ICD10.put("Candiasis","Certain infectious and parasitic diseases","B37");
ICD10.put("Coccidiodomycosis","Certain infectious and parasitic diseases","B38");
ICD10.put("Blastomycosis","Certain infectious and parasitic diseases","B40");
ICD10.put("Histoplasmosis","Certain infectious and parasitic diseases","B39");
ICD10.put("Paracoccidioidomycosis","Certain infectious and parasitic diseases","B41");
ICD10.put("Sporotrichosis","Certain infectious and parasitic diseases","B42");
ICD10.put("Chromomycosis and phaemycotic abscess","Certain infectious and parasitic diseases","B43");
ICD10.put("Aspergillosis","Certain infectious and parasitic diseases","B44");
ICD10.put("Cryptococcosis","Certain infectious and parasitic diseases","B45");
ICD10.put("Zygomycosis","Certain infectious and parasitic diseases","B46");
ICD10.put("Mycetoma","Certain infectious and parasitic diseases","B47");
ICD10.put("Plasmodium falciparium malaria","Certain infectious and parasitic diseases","B50");
ICD10.put("Plasmodium vivax malaria","Certain infectious and parasitic diseases","B51");
ICD10.put("Plasmodium malariae malaria","Certain infectious and parasitic diseases","B52");
ICD10.put("Unspecified malaria","Certain infectious and parasitic diseases","B54");
ICD10.put("Leishmaniasis","Certain infectious and parasitic diseases","B55");
ICD10.put("African trypanosomiasis","Certain infectious and parasitic diseases","B56");
ICD10.put("Chagas disease","Certain infectious and parasitic diseases","B57");
ICD10.put("Toxoplasmosis","Certain infectious and parasitic diseases","B58");
ICD10.put("Pneumocystosis","Certain infectious and parasitic diseases","B59");
ICD10.put("Schistonosomiasis","Certain infectious and parasitic diseases","B65");
ICD10.put("Opisthorchiasis","Certain infectious and parasitic diseases","B66.0");
ICD10.put("Clonorchiasis","Certain infectious and parasitic diseases","B66.1");
ICD10.put("Dicrocoeliasis","Certain infectious and parasitic diseases","B66.2");
ICD10.put("Fascioliasis","Certain infectious and parasitic diseases","B66.3");
ICD10.put("Paragonimiasis","Certain infectious and parasitic diseases","B66.4");
ICD10.put("Fasciolopsiasis","Certain infectious and parasitic diseases","B66.5");
ICD10.put("Echinococcosis","Certain infectious and parasitic diseases","B67");
ICD10.put("Taeniasis","Certain infectious and parasitic diseases","B68");
ICD10.put("Cysticerosis","Certain infectious and parasitic diseases","B69");
ICD10.put("Diphyllobothriasis and sparganosis","Certain infectious and parasitic diseases","B70");
ICD10.put("Hymenolepiasis","Certain infectious and parasitic diseases","B71.0");
ICD10.put("Dipylidiasis","Certain infectious and parasitic diseases","B71.1");
ICD10.put("Dracunculiasis","Certain infectious and parasitic diseases","B72");
ICD10.put("Onchocerciasis","Certain infectious and parasitic diseases","B73");
ICD10.put("Filariasis","Certain infectious and parasitic diseases","B74");
ICD10.put("Trichinellosis","Certain infectious and parasitic diseases","B75");
ICD10.put("Ancylostomiasis","Certain infectious and parasitic diseases","B76.0");
ICD10.put("Necatoriasis","Certain infectious and parasitic diseases","B76.1");
ICD10.put("Ascariasis","Certain infectious and parasitic diseases","B77");
ICD10.put("Strongyloidiasis","Certain infectious and parasitic diseases","B78");
ICD10.put("Trichuriasis","Certain infectious and parasitic diseases","B79");
ICD10.put("Enterobiasis","Certain infectious and parasitic diseases","B80");
ICD10.put("Pediculosis and phthiriasis","Certain infectious and parasitic diseases","B85");
ICD10.put("Scabies","Certain infectious and parasitic diseases","B86");
ICD10.put("Myiasis","Certain infectious and parasitic diseases","B87");
ICD10.put("Sequelae of tuberculosis","Certain infectious and parasitic diseases","B90");
ICD10.put("Sequelaea of poliomyelitis","Certain infectious and parasitic diseases","B91");
ICD10.put("Sequelaea of leprosy","Certain infectious and parasitic diseases","B92");
ICD10.put("Malignant neoplasm of lip","Neoplasms","C00");
ICD10.put("Malignant neoplasm of base of tongue","Neoplasms","C01");
ICD10.put("Malignant neoplasm of other and unspecified part of tongue","Neoplasms","C02");
ICD10.put("Malignant neoplasm of gum","Neoplasms","C03");
ICD10.put("Malignant neoplasm of floor of mouth","Neoplasms","C04");
ICD10.put("Malignant neoplasm of palate","Neoplasms","C05");
ICD10.put("Malignant neoplasm of other and unspecified parts of mouth","Neoplasms","C06");
ICD10.put("Malignant neoplasm of parotid gland","Neoplasms","C07");
ICD10.put("Malignant neoplasm of other and unspecified major salivary glands","Neoplasms","C08");
ICD10.put("Malignant neoplasm of tonsil","Neoplasms","C09");
ICD10.put("Malignant neoplasm of oropharynx","Neoplasms","C10");
ICD10.put("Malignant neoplasm of nasopharynx","Neoplasms","C11");
ICD10.put("Malignant neoplasm of piriform sinus","Neoplasms","C12");
ICD10.put("Malignant neoplasm of hypopharynx","Neoplasms","C13");
ICD10.put("Malignant neoplasm of other and ill-defined sites in the lip, oral cavity and pharix","Neoplasms","C14");
ICD10.put("Malignant neoplasm of oesophagus","Neoplasms","C15");
ICD10.put("Malignant neoplasm of stomach","Neoplasms","C16");
ICD10.put("Malignant neoplasm of small intestine","Neoplasms","C17");
ICD10.put("Malignant neoplasm of colon","Neoplasms","C18");
ICD10.put("Malignant neoplasm of rectosigmoid junction","Neoplasms","C19");
ICD10.put("Malignant neoplasm of rectum","Neoplasms","C20");
ICD10.put("Malignant neoplasm of anus and anal canal","Neoplasms","C21");
ICD10.put("Malignant neoplasm of liver and intrahepatic bile ducts","Neoplasms","C22");
ICD10.put("Malignant neoplasm of gallbladder","Neoplasms","C23");
ICD10.put("Malignant neoplasm of other and unspecified parts of biliary tract","Neoplasms","C24");
ICD10.put("Malignant neoplasm of pancreas","Neoplasms","C25");
ICD10.put("Malignant neoplasm of other and ill-defined digestive organs","Neoplasms","C26");
 ICD10.put("Malignant neoplasm of nasal cavity and middle ear","Neoplasms","C30");
ICD10.put("Malignant neoplasm of accessory sinuses","Neoplasms","C31");
ICD10.put("Malignant neoplasm of larynx","Neoplasms","C32");
ICD10.put("Malignant neoplasm of trachea","Neoplasms","C33");
ICD10.put("Malignant neoplasm of bronchus and lung","Neoplasms","C34");
ICD10.put("Malignant neoplasm of thymus","Neoplasms","C37");
ICD10.put("Malignant neoplasm of heart","Neoplasms","C38");
ICD10.put("Malignant neoplasm of bone and articular cartilage of limbs","Neoplasms","C40");
ICD10.put("Malignant melanoma of skin","Neoplasms","C43");
ICD10.put("Mesothelioma","Neoplasms","C45");
ICD10.put("Kaposi sarcoma","Neoplasms","C46");
ICD10.put("Malignant neoplasm of peripheral nerves and autonomic nervous system","Neoplasms","C47");
ICD10.put("Malignant neoplasm of breast","Neoplasms","C50");
ICD10.put("Malignant neoplasm of kidney","Neoplasms","C64");
ICD10.put("Malignant neoplasm of ureter","Neoplasms","C66");
ICD10.put("Malignant neoplasm of renal pelvis","Neoplasms","C65");
ICD10.put("Malignant neoplasm of bladder","Neoplasms","C67");
ICD10.put("Malignant neoplasm of eye and adnexa","Neoplasms","C69");
ICD10.put("Malignant neoplasm of meninges","Neoplasms","C70");
ICD10.put("Malignant neoplasm of brain","Neoplasms","C71");
ICD10.put("Malignant neoplasm of spinal cord","Neoplasms","C72");
ICD10.put("Malignant neoplasm of thyroid gland","Neoplasms","C73");
ICD10.put("Malignant neoplasm of adrenal gland","Neoplasms","C74");
ICD10.put("Hodgkin lymphoma","Neoplasms","C81");
ICD10.put("Follicular lymphoma","Neoplasms","C82");
ICD10.put("Non-follicular lymphoma","Neoplasms","C83");
ICD10.put("Mature T/NK-cell lymphomas","Neoplasms","C84");
ICD10.put("Multiple myeloma","Neoplasms","C90.0");
ICD10.put("Plasma cell leukemia","Neoplasms","C90.1");
ICD10.put("Lymphoid leukaemia","Neoplasms","C91");
ICD10.put("Myeloid leukaemia","Neoplasms","C92");
ICD10.put("Monocytic leukaemia","Neoplasms","C93");
ICD10.put("Iron deficiency anaemia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D50");
ICD10.put("Vitamin B12 deficiency anaemia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D51");
ICD10.put("Folate deficiency anaemia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D52");
ICD10.put("Alpha thalassaemia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D56.0");
ICD10.put("Beta thalassaemia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D56.1");
ICD10.put("Delta-beta thalassaemia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D56.2");
ICD10.put("Sickle-cell anaemia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D57");
ICD10.put("Acquired haemolytic anaemia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D59");
ICD10.put("Acquired pure red cell aplasia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D60");
ICD10.put("Acute posthaemorrhagic anaemia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D62");
ICD10.put("Agranulocytosis","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D70");
ICD10.put("Genetic anomalies of leukocytes","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D72.0");
ICD10.put("Eosinophilia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D72.1");
ICD10.put("Hyposplenism","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D73.0");
ICD10.put("Hypersplenism","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D73.1");
ICD10.put("Chronic congestive splenomegaly","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D73.2");
ICD10.put("Methaemoglobinaemia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D74");
ICD10.put("Hereditary hypogammaglobulinaemia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D80.0");
ICD10.put("Nonfamilial hypogammaglobulinaemia","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D80.1");
ICD10.put("Wiskott-Aldrich syndrome","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D82.0");
ICD10.put("Di George syndrome","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D82.1");
ICD10.put("Immunodeficiency with short-limbed stature","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D82.2");
ICD10.put("Common variable immunodeficiency","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D83");
ICD10.put("Sarcoidosis","Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism","D86");
ICD10.put("Congenital iodine-deficiency syndrome","Endocrine, nutritional and metabolic diseases","E00");
ICD10.put("Iodine-deficiency-related thyroid disorder","Endocrine, nutritional and metabolic diseases","E01");
ICD10.put("Subclinical iodine-deficiency hypothyroidism","Endocrine, nutritional and metabolic diseases","E02");
ICD10.put("Nontoxic diffuse goitre","Endocrine, nutritional and metabolic diseases","E04.0");
ICD10.put("Nontoxic single thyroid nodule","Endocrine, nutritional and metabolic diseases","E04.1");
ICD10.put("Nontoxic multinodular goitre","Endocrine, nutritional and metabolic diseases","E04.2");
ICD10.put("Thyroiditis","Endocrine, nutritional and metabolic diseases","E06");
ICD10.put("Type 1 diabetes melitus","Endocrine, nutritional and metabolic diseases","E10");
ICD10.put("Type 2 diabetes melitus","Endocrine, nutritional and metabolic diseases","E11");
ICD10.put("Malnutrition-related diabetes melitus","Endocrine, nutritional and metabolic diseases","E12");
ICD10.put("Hypoparathyroidism","Endocrine, nutritional and metabolic diseases","E20");
ICD10.put("Hyperparathyroidism and other disorders of parathyroid gland","Endocrine, nutritional and metabolic diseases","E21");
ICD10.put("Hyperfunction of pituitary gland","Endocrine, nutritional and metabolic diseases","E22");
ICD10.put("Hypofunction and other disorders of pituitary gland","Endocrine, nutritional and metabolic diseases","E23");
ICD10.put("Cushing syndrome","Endocrine, nutritional and metabolic diseases","E24");
ICD10.put("Adrenogenital disorders","Endocrine, nutritional and metabolic diseases","E25");
ICD10.put("Hyperaldosteronism","Endocrine, nutritional and metabolic diseases","E26");
ICD10.put("Ovarian dysfunction","Endocrine, nutritional and metabolic diseases","E28");
ICD10.put("Testicular dysfunction","Endocrine, nutritional and metabolic diseases","E29");
ICD10.put("Polyglandular dysfunction","Endocrine, nutritional and metabolic diseases","E31");
ICD10.put("Kwashiorkor","Endocrine, nutritional and metabolic diseases","E40");
ICD10.put("Nutritional marasmus","Endocrine, nutritional and metabolic diseases","E41");
ICD10.put("Marasmic kwashiorkor","Endocrine, nutritional and metabolic diseases","E42");
ICD10.put("Vitamin A deficiency","Endocrine, nutritional and metabolic diseases","E50");
ICD10.put("Thiamine deficiency","Endocrine, nutritional and metabolic diseases","E51");
ICD10.put("Niacin deficiency","Endocrine, nutritional and metabolic diseases","E52");
ICD10.put("Ascorbic acid deficiency","Endocrine, nutritional and metabolic diseases","E54");
ICD10.put("Vitamin D deficiency","Endocrine, nutritional and metabolic diseases","E55");
ICD10.put("Deficiency of vitamin E","Endocrine, nutritional and metabolic diseases","E56.0");
ICD10.put("Deficiency of vitamin K","Endocrine, nutritional and metabolic diseases","E56.1");
ICD10.put("Dietary calcium deficiency","Endocrine, nutritional and metabolic diseases","E58");
ICD10.put("Localized adiposity","Endocrine, nutritional and metabolic diseases","E65");
ICD10.put("Obesity","Endocrine, nutritional and metabolic diseases","E66");
ICD10.put("Classical phenylketonuria","Endocrine, nutritional and metabolic diseases","E70.0");
ICD10.put("Albinism","Endocrine, nutritional and metabolic diseases","E70.3");
ICD10.put("Lactose intolerance","Endocrine, nutritional and metabolic diseases","E73");
ICD10.put("Glycogen storage disease","Endocrine, nutritional and metabolic diseases","E74.0");
ICD10.put("Disorders of fructose metabolism","Endocrine, nutritional and metabolic diseases","E74.1");
ICD10.put("Disorders of galactose metabolism","Endocrine, nutritional and metabolic diseases","E74.2");
ICD10.put("Pure hypercholesterolaemia","Endocrine, nutritional and metabolic diseases","E78.0");
ICD10.put("Pure hyperglyceridaemia","Endocrine, nutritional and metabolic diseases","E78.1");
ICD10.put("Mixed hyperlipidaemia","Endocrine, nutritional and metabolic diseases","E78.2");
ICD10.put("Hyperchylomicronaemia","Endocrine, nutritional and metabolic diseases","E78.3");
ICD10.put("E84","Cystic fibrosis","Endocrine, nutritional and metabolic diseases");
ICD10.put("Amyloidosis","Endocrine, nutritional and metabolic diseases","E85");
ICD10.put("Volume depletion","Endocrine, nutritional and metabolic diseases","E86");
ICD10.put("Hyperosmolality and hypernatraemia","Endocrine, nutritional and metabolic diseases","E87.0");
ICD10.put("Acidosis","Endocrine, nutritional and metabolic diseases","E87.2");
ICD10.put("Alkalosis","Endocrine, nutritional and metabolic diseases","E87.3");
ICD10.put("Hyperkalaemia","Endocrine, nutritional and metabolic diseases","E87.5");
ICD10.put("Hypokalaemia","Endocrine, nutritional and metabolic diseases","E87.6");
ICD10.put("Fluid overload","Endocrine, nutritional and metabolic diseases","E87.7");
ICD10.put("Dementia in Alzheimer disease","Endocrine, nutritional and metabolic diseases","F00");
ICD10.put("Vascular dementia","Endocrine, nutritional and metabolic diseases","F01");
ICD10.put("Delirium","Endocrine, nutritional and metabolic diseases","F05");
ICD10.put("Mental and behavioural disorders due to use of alcohol:acute intoxication","Endocrine, nutritional and metabolic diseases","F10.0");
ICD10.put("Mental and behavioural disorders due to use of alcohol:harmful use","Endocrine, nutritional and metabolic diseases","F10.1");
ICD10.put("Mental and behavioural disorders due to use of alcohol:dependence syndrome","Endocrine, nutritional and metabolic diseases","F10.2");
ICD10.put("Mental and behavioural disorders due to use of alcohol withdrawal state","Endocrine, nutritional and metabolic diseases","F10.3");
ICD10.put("Mental and behavioural disorders due to use of opioids","Endocrine, nutritional and metabolic diseases","F11");
ICD10.put("Mental and behavioural disorders due to use of cannabinoids","Endocrine, nutritional and metabolic diseases","F12");
ICD10.put("Mental and behavioural disorders due to use of sedatives or hypnotics","Endocrine, nutritional and metabolic diseases","F13");
ICD10.put("Mental and behavioural disorders due to use of cocaine","Endocrine, nutritional and metabolic diseases","F14");
ICD10.put("Mental and behavioural disorders due to use of hallucinogens","Endocrine, nutritional and metabolic diseases","F16");
ICD10.put("Mental and behavioural disorders due to use of sedatives or tobacco","Endocrine, nutritional and metabolic diseases","F17");
ICD10.put("Schizophrenia","Endocrine, nutritional and metabolic diseases","F20");
ICD10.put("Schizotypal disorder","Endocrine, nutritional and metabolic diseases","F21");
ICD10.put("Persistent delusional disorders","Endocrine, nutritional and metabolic diseases","F22");
ICD10.put("Induced delusional disorder","Endocrine, nutritional and metabolic diseases","F24");
ICD10.put("Manic episode","Endocrine, nutritional and metabolic diseases","F30");
ICD10.put("Bipolar affective disorder","Endocrine, nutritional and metabolic diseases","F31");
ICD10.put("Depressive episode","Endocrine, nutritional and metabolic diseases","F32");
ICD10.put("Recurrent depressive disorder","Endocrine, nutritional and metabolic diseases","F33");
ICD10.put("Agoraphobia","Endocrine, nutritional and metabolic diseases","F40.0");
ICD10.put("Social phobias","Endocrine, nutritional and metabolic diseases","F40.1");
ICD10.put("Panic disorder","Endocrine, nutritional and metabolic diseases","F41.0");
ICD10.put("Obsessive-compulsive disorder","Endocrine, nutritional and metabolic diseases","F42");
ICD10.put("Post-traumatic stress disorder","Endocrine, nutritional and metabolic diseases","F43.1");
ICD10.put("Dissociative amnesia","Endocrine, nutritional and metabolic diseases","F44.0");
ICD10.put("Neurasthenia","Endocrine, nutritional and metabolic diseases","F48.0");
ICD10.put("Anorexia nervosa","Endocrine, nutritional and metabolic diseases","F50.0");
ICD10.put("Atypical anorexia nervosa","Endocrine, nutritional and metabolic diseases","F50.1");
ICD10.put("Bulimia nervosa","Endocrine, nutritional and metabolic diseases","F50.2");
ICD10.put("Atypical bulimia nervosa","Endocrine, nutritional and metabolic diseases","F50.3");
ICD10.put("Nonorganic insomnia","Endocrine, nutritional and metabolic diseases","F51.0");
ICD10.put("Nonorganic hypersomnia","Endocrine, nutritional and metabolic diseases","F51.1");
ICD10.put("Sleepwalking[somnambulism]","Endocrine, nutritional and metabolic diseases","F51.3");
ICD10.put("Sleep terrors","Endocrine, nutritional and metabolic diseases","F51.4");
ICD10.put("Sexual dysfunction","Endocrine, nutritional and metabolic diseases","F52");
ICD10.put("Paranoid personality disorder","Endocrine, nutritional and metabolic diseases","F60.0");
ICD10.put("Schizoid personality disorder","Endocrine, nutritional and metabolic diseases","F60.1");
ICD10.put("Dissocial personality disorder","Endocrine, nutritional and metabolic diseases","F60.2");
ICD10.put("Pathological gambling","Endocrine, nutritional and metabolic diseases","F63.0");
ICD10.put("Pathological fire-setting[pyromania]","Endocrine, nutritional and metabolic diseases","F63.1");
ICD10.put("Pathological stealing[kleptomania]","Endocrine, nutritional and metabolic diseases","F63.2");
ICD10.put("Trichotillomania","Endocrine, nutritional and metabolic diseases","F63.3");
ICD10.put("Mild mental retardation","Endocrine, nutritional and metabolic diseases","F70");
ICD10.put("Moderate mental retardation","Endocrine, nutritional and metabolic diseases","F71");
ICD10.put("Severe mental retardation","Endocrine, nutritional and metabolic diseases","F72");
ICD10.put("Profound mental retardation","Endocrine, nutritional and metabolic diseases","F73");
ICD10.put("Hyperkinetic disorder","Endocrine, nutritional and metabolic diseases","F90");
ICD10.put("Conduct disorder","Endocrine, nutritional and metabolic diseases","F91");
ICD10.put("Bacterial meningitis","Diseases of the nervous system","G00");
ICD10.put("Encephalitis","Diseases of the nervous system","G04");
ICD10.put("Huntington disease","Diseases of the nervous system","G10");
ICD10.put("Hereditary ataxia","Diseases of the nervous system","G11");
ICD10.put("Postpolio syndrome","Diseases of the nervous system","G14");
ICD10.put("Parkinson disease","Diseases of the nervous system","G20");
ICD10.put("Secondary parkinsonism","Diseases of the nervous system","G21");
ICD10.put("Dystonia","Diseases of the nervous system","G24");
ICD10.put("Alzheimer disease with early onset","Diseases of the nervous system","G30.0");
ICD10.put("Alzheimer disease with late onset","Diseases of the nervous system","G30.1");
ICD10.put("Multiple sclerosis","Diseases of the nervous system","G35");
ICD10.put("Epilepsy","Diseases of the nervous system","G40");
ICD10.put("Status epilepticus","Diseases of the nervous system","G41");
ICD10.put("Migraine","Diseases of the nervous system","G43");
ICD10.put("Cluster headache syndrome","Diseases of the nervous system","G44.0");
ICD10.put("Tension-type headache","Diseases of the nervous system","G44.2");
ICD10.put("Chronic post-traumatic headache","Diseases of the nervous system","G44.3");
ICD10.put("Sleep apnoea","Diseases of the nervous system","G47.3");
ICD10.put("Narcolepsy and cataplexy","Diseases of the nervous system","G47.4");
ICD10.put("Trigeminal neuralgia","Diseases of the nervous system","G50.0");
ICD10.put("Atypical facial pain","Diseases of the nervous system","G50.1");
ICD10.put("Bell palsy","Diseases of the nervous system","G51.0");
ICD10.put("Geniculate  ganglionitis","Diseases of the nervous system","G51.1");
ICD10.put("Melkersson syndrome","Diseases of the nervous system","G51.2");
ICD10.put("Clonic hemifacial spasm","Diseases of the nervous system","G51.3");
ICD10.put("Facial myokymia","Diseases of the nervous system","G51.4");
ICD10.put("Postzoster neuralgia","Diseases of the nervous system","G53.0");
ICD10.put("Brachial plexus disorders","Diseases of the nervous system","G54.0");
ICD10.put("Lumbosacral plexus disorders","Diseases of the nervous system","G54.1");
ICD10.put("Carpal tunnel syndrome","Diseases of the nervous system","G56.0");
ICD10.put("Lesion of ulnar nerve","Diseases of the nervous system","G56.2");
ICD10.put("Lesion of radial nerve","Diseases of the nervous system","G56.3");
ICD10.put("Causalgia","Diseases of the nervous system","G56.4");
ICD10.put("Hereditary and idiopathic neuropathy","Diseases of the nervous system","G60");
ICD10.put("Inflammatory polyneuropathy","Diseases of the nervous system","G61");
ICD10.put("Muscular dystrophy","Diseases of the nervous system","G71.0");
ICD10.put("Myotonic disorders","Diseases of the nervous system","G71.1");
ICD10.put("Celebral palsy","Diseases of the nervous system","G80");
ICD10.put("Hemiplegia","Diseases of the nervous system","G81");
ICD10.put("Paraplegia and tetraplegia","Diseases of the nervous system","G82");
ICD10.put("Hordeolum","Diseases of the eye and adnexa","H00.0");
ICD10.put("Chalazion","Diseases of the eye and adnexa","H00.1");
ICD10.put("Blepharitis","Diseases of the eye and adnexa","H01.0");
ICD10.put("Entropion and trichiasis of eyelid","Diseases of the eye and adnexa","H2.0");
ICD10.put("Ectropion of eyelid","Diseases of the eye and adnexa","H2.1");
ICD10.put("Blepharochalasis","Diseases of the eye and adnexa","H02.2");
ICD10.put("Ptosis of eyelid","Diseases of the eye and adnexa","B02.3");
ICD10.put("Dacryoadenitis","Diseases of the eye and adnexa","H04.0");
ICD10.put("Epiphora","Diseases of the eye and adnexa","H04.2");
ICD10.put("Acute inflammation of orbit","Diseases of the eye and adnexa","H05.0");
ICD10.put("Exophtalmic conditions","Diseases of the eye and adnexa","H05.2");
ICD10.put("Deformity of orbit","Diseases of the eye and adnexa","H05.3");
ICD10.put("Enophthalmos","Diseases of the eye and adnexa","H05.4");
ICD10.put("Conjunctivitis","Diseases of the eye and adnexa","H10");
ICD10.put("Pterygium","Diseases of the eye and adnexa","H11.0");
ICD10.put("Conjunctival degenerations and deposits","Diseases of the eye and adnexa","H11.1");
ICD10.put("Conjunctival scars","Diseases of the eye and adnexa","H11.2");
ICD10.put("Conjunctival haemorrhage","Diseases of the eye and adnexa","H11.3");
ICD10.put("Scleritis","Diseases of the eye and adnexa","H15.0");
ICD10.put("Episcleritis","Diseases of the eye and adnexa","H15.1");
ICD10.put("Keratitis","Diseases of the eye and adnexa","H16");
ICD10.put("Bullous keratopathy","Diseases of the eye and adnexa","H18.1");
ICD10.put("Corneal degeneration","Diseases of the eye and adnexa","H18.4");
ICD10.put("Hereditary corneal dystrophies","Diseases of the eye and adnexa","H18.5");
ICD10.put("Keratoconus","Diseases of the eye and adnexa","H18.6");
ICD10.put("Iridocyclitis","Diseases of the eye and adnexa","H20");
ICD10.put("Senile cataract","Diseases of the eye and adnexa","H25");
ICD10.put("Aphakia","Diseases of the eye and adnexa","H27.0");
ICD10.put("Dislocation of lens","Diseases of the eye and adnexa","H27.1");
ICD10.put("Chorioretinal inflammation","Diseases of the eye and adnexa","H30.0");
ICD10.put("Transient retinal artery occlusion","Diseases of the eye and adnexa","H34.0");
ICD10.put("Central retinal artery occlusion","Diseases of the eye and adnexa","H34.1");
ICD10.put("Glaucoma","Diseases of the eye and adnexa","H40");
ICD10.put("Vitreous prolapse","Diseases of the eye and adnexa","H43.0");
ICD10.put("Vitreous haemorrhage","Diseases of the eye and adnexa","H43.1");
ICD10.put("Crystalline deposits in vitreous body","Diseases of the eye and adnexa","H43.2");
ICD10.put("Purulent endophtalmitis","Diseases of the eye and adnexa","H44.0");
ICD10.put("Degenerative myopia","Diseases of the eye and adnexa","H44.2");
ICD10.put("Hypotony of eye","Diseases of the eye and adnexa","H44.4");
ICD10.put("Optic neuritis","Diseases of the eye and adnexa","H46");
ICD10.put("Papilloedema","Diseases of the eye and adnexa","H47.1");
ICD10.put("Optic atrophy","Diseases of the eye and adnexa","H47.2");
ICD10.put("Paralytic strabismus","Diseases of the eye and adnexa","H49");
ICD10.put("Palsy of conjugate gaze","Diseases of the eye and adnexa","H51.0");
ICD10.put("Convergence insufficiency and excess","Diseases of the eye and adnexa","H51.1");
ICD10.put("Internuclear ophtalmoplegia","Diseases of the eye and adnexa","H51.2");
ICD10.put("Amylopia ex anopsia","Diseases of the eye and adnexa","H53.0");
ICD10.put("Subjective visual disturbance","Diseases of the eye and adnexa","H53.1");
ICD10.put("Diplopia","Diseases of the eye and adnexa","H53.2");
ICD10.put("Color vision deficiencies","Diseases of the eye and adnexa","H53.5");
ICD10.put("Night blindness","Diseases of the eye and adnexa","H53.6");
ICD10.put("Otitis externa","Diseases of the ear and mastoid process","H60");
ICD10.put("Nonsuppurative otitis media","Diseases of the ear and mastoid process","H65");
ICD10.put("Suppurative otitis media","Diseases of the ear and mastoid process","H66");
ICD10.put("Eustachian salpingitis","Diseases of the ear and mastoid process","H68.0");
ICD10.put("Obstruction of Eustachian tube","Diseases of the ear and mastoid process","H68.1");
ICD10.put("Acute mastoiditis","Diseases of the ear and mastoid process","H70.0");
ICD10.put("Chronic mastoiditis","Diseases of the ear and mastoid process","H71.1");
ICD10.put("Petrositis","Diseases of the ear and mastoid process","H70.2");
ICD10.put("Cholesteatoma of middle ear","Diseases of the ear and mastoid process","H71");
ICD10.put("Ostoclerosis","Diseases of the ear and mastoid process","H80");
ICD10.put("Ménière disease","Diseases of the ear and mastoid process","H81.0");
ICD10.put("Benign paroxysmal vertigo","Diseases of the ear and mastoid process","H81.1");
ICD10.put("Vestibular neuronitis","Diseases of the ear and mastoid process","H81.2");
ICD10.put("Labyrinthitis","Diseases of the ear and mastoid process","H83.0");
ICD10.put("Labyrinthine fistula","Diseases of the ear and mastoid process","H83.1");
ICD10.put("Labyrinthine dysfunction","Diseases of the ear and mastoid process","H83.2");
ICD10.put("Conductive hearing loss","Diseases of the ear and mastoid process","H90");
ICD10.put("Ototoxic hearing loss","Diseases of the ear and mastoid process","H91.0");
ICD10.put("Prebycusis","Diseases of the ear and mastoid process","H91.1");
ICD10.put("Sudden idiopathic hearing loss","Diseases of the ear and mastoid process","H91.2");
ICD10.put("Deaf mutism","Diseases of the ear and mastoid process","H91.3");
ICD10.put("Otalgia","Diseases of the ear and mastoid process","H92.0");
ICD10.put("Otorrhoea","Diseases of the ear and mastoid process","H92.1");
ICD10.put("Otorrhagia","Diseases of the ear and mastoid process","H92.2");
ICD10.put("Tinnitus","Diseases of the ear and mastoid process","H93.1");
ICD10.put("Rheumatic fever without mention of heart involvement","Diseases of the circulatory system","I00");
ICD10.put("Rheumatic fever with heart involvement","Diseases of the circulatory system","I01");
ICD10.put("Rheumatic chorea","Diseases of the circulatory system","I02");
ICD10.put("Mitral stenosis","Diseases of the circulatory system","I05.0");
ICD10.put("Rheumatic mitral insufficiency","Diseases of the circulatory system","I05.1");
ICD10.put("Mitral stenosis with insufficiency","Diseases of the circulatory system","I05.2");
ICD10.put("Rheumatic aortic stenosis","Diseases of the circulatory system","I06.0");
ICD10.put("Rheumatic aortic insufficiency","Diseases of the circulatory system","I06.1");
ICD10.put("Rheumatic aortic valve disease","Diseases of the circulatory system","I06.9");
ICD10.put("Tricuspid stenosis","Diseases of the circulatory system","I07.0");
ICD10.put("Tricuspid insufficiency","Diseases of the circulatory system","I07.1");
ICD10.put("Essential hypertension","Diseases of the circulatory system","I10");
ICD10.put("Hypertensive heart disease","Diseases of the circulatory system","I11");
ICD10.put("Hypertensive renal disease","Diseases of the circulatory system","I12");
ICD10.put("Hypertensive heart and renal disease","Diseases of the circulatory system","I13");
ICD10.put("Secondary hypertension","Diseases of the circulatory system","I15");
ICD10.put("Angina pectoris","Diseases of the circulatory system","I20");
ICD10.put("Acute myocardical infarction","Diseases of the circulatory system","I21");
ICD10.put("Subsequent myocardial infarction","Diseases of the circulatory system","I22");
ICD10.put("Pulmonary embolism","Diseases of the circulatory system","I26");
ICD10.put("Acute pericarditis","Diseases of the circulatory system","I30");
ICD10.put("Acute endocarditis","Diseases of the circulatory system","I33");
ICD10.put("Pulmonary valve stenosis","Diseases of the circulatory system","I37.0");
ICD10.put("Pulmonary valve insufficiency","Diseases of the circulatory system","I37.1");
ICD10.put("Endocarditis,valve unspecified","Diseases of the circulatory system","I38");
ICD10.put("Acute myocarditis","Diseases of the circulatory system","I40");
ICD10.put("Cardiomyopathy","Diseases of the circulatory system","I42");
ICD10.put("Atrioventricular block","Diseases of the circulatory system","I44");
ICD10.put("Cardiac arrest","Diseases of the circulatory system","I46");
ICD10.put("Paroxysmal tachycardia","Diseases of the circulatory system","I47");
ICD10.put("Atrial fibrillation and flutter","Diseases of the circulatory system","I48");
ICD10.put("Heart failure","Diseases of the circulatory system","I50");
ICD10.put("Subarachnoid haemorrhage","Diseases of the circulatory system","I60");
ICD10.put("Intracerebral haemorrhage","Diseases of the circulatory system","I61");
ICD10.put("Cerebral infarction","Diseases of the circulatory system","I63");
ICD10.put("Stroke","Diseases of the circulatory system","I64");
ICD10.put("Occlusion and stenosis of precerebral arteries","Diseases of the circulatory system","I65");
ICD10.put("Atherosclerosis","Diseases of the circulatory system","I70");
ICD10.put("Aortic aneurysm","Diseases of the circulatory system","I71");
ICD10.put("Hereditary haemorrhagic telangiectasia","Diseases of the circulatory system","I78.0");
ICD10.put("Naevus","Diseases of the circulatory system","I78.1");
ICD10.put("Phlebitis and thrombophlebitis","Diseases of the circulatory system","I80");
ICD10.put("Portal vein thrombosis","Diseases of the circulatory system","I81");
ICD10.put("Oesophageal varices","Diseases of the circulatory system","I85");
ICD10.put("Sublingual varices","Diseases of the circulatory system","I86.0");
ICD10.put("Scrotal varices","Diseases of the circulatory system","I86.1");
ICD10.put("Pelvic varices","Diseases of the circulatory system","I86.2");
ICD10.put("Vulval varices","Diseases of the circulatory system","I86.3");
ICD10.put("Gastric varices","Diseases of the circulatory system","I86.4");
ICD10.put("Nonspecific lymphadenitis","Diseases of the circulatory system","I88");
ICD10.put("Hypotension","Diseases of the circulatory system","I95");
ICD10.put("Acute nasopharyngitis[common cold]","","J00");
ICD10.put("Acute sinusitis","Diseases of the respiratory system","J01");
ICD10.put("Acute pharyngitis","Diseases of the respiratory system","J02");
ICD10.put("Acute tonsilitis","Diseases of the respiratory system","J03");
ICD10.put("Acute laryngitis and tracheitis","Diseases of the respiratory system","J04");
ICD10.put("Acute obstructive laryngitis and tracheitis","Diseases of the respiratory system","J05");
ICD10.put("Influenza due to identified zoonotic or pandemic influenza virus","Diseases of the respiratory system","J09");
ICD10.put("Influenza due to identified seasonal influenza","Diseases of the respiratory system","J10");
ICD10.put("Influenza,virus not identified","Diseases of the respiratory system","J11");
ICD10.put("Viral pneumonia,not elsewhere classified","Diseases of the respiratory system","J12");
ICD10.put("Pneumonia due to Streptococcus pneumoniae","Diseases of the respiratory system","J13");
ICD10.put("Pneumonia due to Haemophilius influenzae","Diseases of the respiratory system","J14");
ICD10.put("Bacterial pneumonia","Diseases of the respiratory system","J15");
ICD10.put("Acute bronchitis","Diseases of the respiratory system","J20");
ICD10.put("Acute bronchiolitis","Diseases of the respiratory system","J21");
ICD10.put("Vasomotor and allergic rhinitis","Diseases of the respiratory system","J30");
ICD10.put("Chronic rhinitis","Diseases of the respiratory system","J31.0");
ICD10.put("Chronic nasopharyngitis","Diseases of the respiratory system","J31.1");
ICD10.put("Chronic pharyngitis","Diseases of the respiratory system","J31.2");
ICD10.put("Chronic sinusitis","Diseases of the respiratory system","J32");
ICD10.put("Nasal polyp","Diseases of the respiratory system","J33");
ICD10.put("Chronic tonsilitis","Diseases of the respiratory system","J35.0");
ICD10.put("Hypertrophy of tonsils","Diseases of the respiratory system","J35.1");
ICD10.put("Hypertrophy of adenoid","Diseases of the respiratory system","J35.2");
ICD10.put("Peritonsilar abscess","Diseases of the respiratory system","J36");
ICD10.put("Chronic laryngitis","Diseases of the respiratory system","J37.0");
ICD10.put("Chronic laryngotracheitis","Diseases of the respiratory system","J37.1");
ICD10.put("Paralysis of vocal cords and larynx","Diseases of the respiratory system","J38.0");
ICD10.put("Nodules of vocal cords","Diseases of the respiratory system","J38.2");
ICD10.put("Oedema of larynx","Diseases of the respiratory system","J38.4");
ICD10.put("Bronchitis","Diseases of the respiratory system","J40");
ICD10.put("Simple chronic bronchitis","Diseases of the respiratory system","J41.0");
ICD10.put("Mucopurulent chronic bronchitis","Diseases of the respiratory system","J41.1");
ICD10.put("Unspecified chronic bronchitis","Diseases of the respiratory system","J42");
ICD10.put("Emphysema","Diseases of the respiratory system","J43");
ICD10.put("Asthma","Diseases of the respiratory system","J45");
ICD10.put("Status asthmaticus","Diseases of the respiratory system","J46");
ICD10.put("Bronchiectasis","Diseases of the respiratory system","J47");
ICD10.put("Coalworker pneumoconiosis","Diseases of the respiratory system","J60");
ICD10.put("Pneumoconiosis due to asbestos","Diseases of the respiratory system","J61");
ICD10.put("Pneumoconiosis due to dust containing silica","Diseases of the respiratory system","J62");
ICD10.put("Unspecfied pneumoconiosis","Diseases of the respiratory system","J64");
ICD10.put("Pneumoconiosis associated with tuberculosis","Diseases of the respiratory system","J65");
ICD10.put("Pneumonitis due to solids and liquids","Diseases of the respiratory system","J69");
ICD10.put("Adult respiratory  distress syndrome","Diseases of the respiratory system","J80");
ICD10.put("Pulmonary oedema","Diseases of the respiratory system","J81");
ICD10.put("Pulmonary eosinophilia","Diseases of the respiratory system","J82");
ICD10.put("Pleural effusion","Diseases of the respiratory system","J90");
ICD10.put("Pleural plaque","Diseases of the respiratory system","J92");
ICD10.put("Pneumothorax","Diseases of the respiratory system","J93");
ICD10.put("Anodontia","Diseases of the digestive system","K00.0");
ICD10.put("Supernumerary teeth","Diseases of the digestive system","K00.1");
ICD10.put("Abnormalities of size and form of teeth","Diseases of the digestive system","K00.2");
ICD10.put("Mottled teeth","Diseases of the digestive system","K00.3");
ICD10.put("Disturbances in tooth formation","Diseases of the digestive system","K00.4");
ICD10.put("Disturbances in tooth eruption","Diseases of the digestive system","K00.6");
ICD10.put("Teething syndrome","Diseases of the digestive system","K00.7");
ICD10.put("Dental caries","Diseases of the digestive system","K02");
ICD10.put("Pulpitis","Diseases of the digestive system","K04.0");
ICD10.put("Necrosis of pulp","Diseases of the digestive system","K04.1");
ICD10.put("Pulp degeneration","Diseases of the digestive system","K04.2");
ICD10.put("Acute gingivitis","Diseases of the digestive system","K05.0");
ICD10.put("Chronic gingivitis","Diseases of the digestive system","K05.1");
ICD10.put("Periodontosis","Diseases of the digestive system","K05.4");
ICD10.put("Gingival recession","Diseases of the digestive system","K06.0");
ICD10.put("Gingival enlargement","Diseases of the digestive system","K06.1");
ICD10.put("Atrophy of salivary gland","Diseases of the digestive system","K11.0");
ICD10.put("Hypertrophy of salivary gland","Diseases of the digestive system","K11.1");
ICD10.put("Sialoadentitis","Diseases of the digestive system","K11.2");
ICD10.put("Abscess of salivary gland","Diseases of the digestive system","K11.3");
ICD10.put("Fistula of salivary gland","Diseases of the digestive system","K11.4");
ICD10.put("Sialolithiasis","Diseases of the digestive system","K11.5");
ICD10.put("Recurrent oral aphthae","Diseases of the digestive system","K12.0");
ICD10.put("Cellulitis and abscess of mouth","Diseases of the digestive system","K12.2");
ICD10.put("Glossitis","Diseases of the digestive system","K14.0");
ICD10.put("Geographic tongue","Diseases of the digestive system","K14.1");
ICD10.put("Median rhomboid glossitis","Diseases of the digestive system","K14.2");
ICD10.put("Hypetrophy of tongue papillae","Diseases of the digestive system","K14.3");
ICD10.put("Atrophy of tongue papillae","Diseases of the digestive system","K14.4");
ICD10.put("Plicated tongue","Diseases of the digestive system","K14.5");
ICD10.put("Glossodynia","Diseases of the digestive system","K14.6");
ICD10.put("Oesophagitis","Diseases of the digestive system","K20");
ICD10.put("Gastro-oesophageal reflux disease","Diseases of the digestive system","K21");
ICD10.put("Gastric ulcer","Diseases of the digestive system","K25");
ICD10.put("Duodenal ulcer","Diseases of the digestive system","K26");
ICD10.put("Peptic ulcer","Diseases of the digestive system","K27");
ICD10.put("Gastrojejunal ulcer","Diseases of the digestive system","K28");
ICD10.put("Gastritis","Diseases of the digestive system","K29");
ICD10.put("Functional dyspepsia","Diseases of the digestive system","K30");
ICD10.put("Acute appendicitis","Diseases of the digestive system","K35");
ICD10.put("Inguinal hernia","Diseases of the digestive system","K40");
ICD10.put("Femoral hernia","Diseases of the digestive system","K41");
ICD10.put("Umbilical hernia","Diseases of the digestive system","K42");
ICD10.put("Ventral hernia","Diseases of the digestive system","K43");
ICD10.put("Diaphragmatic hernia","Diseases of the digestive system","K44");
ICD10.put("Perionitis","Diseases of the digestive system","K65");
ICD10.put("Alcoholic liver disease","Diseases of the digestive system","K70");
ICD10.put("Toxic liver disease","Diseases of the digestive system","K71");
ICD10.put("Hepatic failure","Diseases of the digestive system","K72");
ICD10.put("Chronic hepatitis","Diseases of the digestive system","K73");
ICD10.put("Fibrosis and cirrhosis of liver","Diseases of the digestive system","K74");
ICD10.put("Abscess of liver","Diseases of the digestive system","K75.0");
ICD10.put("Phlebitis of portal vein","Diseases of the digestive system","K75.1");
ICD10.put("Autoimmune hepatits","Diseases of the digestive system","K75.4");
ICD10.put("Fatty liver","Diseases of the digestive system","K76.0");
ICD10.put("Chronic passive congestion of liver","Diseases of the digestive system","F76.1");
ICD10.put("Infarction of liver","Diseases of the digestive system","K76.3");
ICD10.put("Peliosis hepatis","Diseases of the digestive system","K76.4");
ICD10.put("Portal hypertension","Diseases of the digestive system","K76.6");
ICD10.put("Hepatorenal syndrome","Diseases of the digestive system","K76.7");
ICD10.put("Cholelithiasis","Diseases of the digestive system","K80");
ICD10.put("Cholecystitis","Diseases of the digestive system","K81");
ICD10.put("Acute pancreatitis","Diseases of the digestive system","K85");
ICD10.put("Staphylococcal scalded skin syndrome","","L00");
ICD10.put("Impetigo","Diseases of the skin and subcutaneous tissue","L01");
ICD10.put("Cutaneous abscess, furuncle and carbuncle","Diseases of the skin and subcutaneous tissue","L02");
ICD10.put("Cellulitis","Diseases of the skin and subcutaneous tissue","L03");
ICD10.put("Acute lymphadenitis","Diseases of the skin and subcutaneous tissue","L04");
ICD10.put("Pilonidal cyst","Diseases of the skin and subcutaneous tissue","L05");
ICD10.put("Pemphigus","Diseases of the skin and subcutaneous tissue","L10");
ICD10.put("Pemphigoid","Diseases of the skin and subcutaneous tissue","L12");
ICD10.put("Dermatitis herpetiformis","Diseases of the skin and subcutaneous tissue","L13.0");
ICD10.put("Subcorneal pustular dermatitis","Diseases of the skin and subcutaneous tissue","L13.1");
ICD10.put("Atopic dermatitis","Diseases of the skin and subcutaneous tissue","L20");
ICD10.put("Seborrhoeic dermatitis","Diseases of the skin and subcutaneous tissue","L21");
ICD10.put("Diaper dermatitis","Diseases of the skin and subcutaneous tissue","L22");
ICD10.put("Allergic contact dermatitis","Diseases of the skin and subcutaneous tissue","L23");
ICD10.put("Irritant contact dermatitis","Diseases of the skin and subcutaneous tissue","L24");
ICD10.put("Exfoliative dermatitis","Diseases of the skin and subcutaneous tissue","L26");
ICD10.put("Lichen simplex chronicus and prurigo","Diseases of the skin and subcutaneous tissue","L28");
ICD10.put("Pruritus","Diseases of the skin and subcutaneous tissue","L29");
ICD10.put("Psoriasis","Diseases of the skin and subcutaneous tissue","L40");
ICD10.put("Parapsoriasis","Diseases of the skin and subcutaneous tissue","L41");
ICD10.put("Pityriasis rosea","Diseases of the skin and subcutaneous tissue","L42");
ICD10.put("Lichen planus","Diseases of the skin and subcutaneous tissue","L43");
ICD10.put("Urticaria","Diseases of the skin and subcutaneous tissue","L50");
ICD10.put("Erythema multiforme","Diseases of the skin and subcutaneous tissue","L51");
ICD10.put("Erythema nodosum","Diseases of the skin and subcutaneous tissue","L52");
ICD10.put("Sunburn","Diseases of the skin and subcutaneous tissue","L55");
ICD10.put("Actinic keratosis","Diseases of the skin and subcutaneous tissue","L57.0");
ICD10.put("Actinic reticuloid","Diseases of the skin and subcutaneous tissue","L57.1");
ICD10.put("Cutis rhomboidalis nuchae","Diseases of the skin and subcutaneous tissue","L57.2");
ICD10.put("Poikiloderma of Civatte","Diseases of the skin and subcutaneous tissue","L57.3");
ICD10.put("Cutis laxa senilis","Diseases of the skin and subcutaneous tissue","L57.4");
ICD10.put("Actinic granuloma","Diseases of the skin and subcutaneous tissue","L57.5");
ICD10.put("Radiodermatitis","Diseases of the skin and subcutaneous tissue","L58");
ICD10.put("Alopecia areata","Diseases of the skin and subcutaneous tissue","L63");
ICD10.put("Androgenic alopecia","Diseases of the skin and subcutaneous tissue","L64");
ICD10.put("Cicatricial alopecia","Diseases of the skin and subcutaneous tissue","L66");
ICD10.put("Hypertrichosis","Diseases of the skin and subcutaneous tissue","L68");
ICD10.put("Acne","Diseases of the skin and subcutaneous tissue","L70");
ICD10.put("Rosacea","Diseases of the skin and subcutaneous tissue","L71");
ICD10.put("Vitiligo","Diseases of the skin and subcutaneous tissue","L80");
ICD10.put("Seborrhoeic keratosis","Diseases of the skin and subcutaneous tissue","L82");
ICD10.put("Acanthosis nigricans","Diseases of the skin and subcutaneous tissue","L83");
ICD10.put("Corns and callosites","Diseases of the skin and subcutaneous tissue","L84");
ICD10.put("Keratoderma in disease classified elsewhere","Diseases of the skin and subcutaneous tissue","L86");
ICD10.put("Pyoderma gangrenosum","Diseases of the skin and subcutaneous tissue","L88");
ICD10.put("Lupus erythematosus","Diseases of the skin and subcutaneous tissue","L93");
ICD10.put("Linear scleroderma","Diseases of the skin and subcutaneous tissue","L94.1");
ICD10.put("Calcinosis cutis","Diseases of the skin and subcutaneous tissue","L94.2");
ICD10.put("Sclerodactyly","Diseases of the skin and subcutaneous tissue","L94.3");
ICD10.put("Gotron papules","Diseases of the skin and subcutaneous tissue","L94.4");
ICD10.put("Ulcer of lower limb","Diseases of the skin and subcutaneous tissue","L97");
ICD10.put("Pyogenic arthritis","Diseases of the musculoskeletal system and connective tissue","M00");
ICD10.put("Ractive athropathies","Diseases of the musculoskeletal system and connective tissue","M02");
ICD10.put("Seropositive rheumatoid arthritis","Diseases of the musculoskeletal system and connective tissue","M05");
ICD10.put("Distal interphalangeal psoriatic arthropathy","Diseases of the musculoskeletal system and connective tissue","M07.0");
ICD10.put("Arthritis mutilans","Diseases of the musculoskeletal system and connective tissue","M07.1");
ICD10.put("Psoriatic spondylitis","Diseases of the musculoskeletal system and connective tissue","M07.2");
ICD10.put("Juvenile arthritis","Diseases of the musculoskeletal system and connective tissue","M08");
ICD10.put("Gout","Diseases of the musculoskeletal system and connective tissue","M10");
ICD10.put("Polyarthrosis","Diseases of the musculoskeletal system and connective tissue","M15");
ICD10.put("Coxarthrosis","Diseases of the musculoskeletal system and connective tissue","M16");
ICD10.put("Gonarthrosis","Diseases of the musculoskeletal system and connective tissue","M17");
ICD10.put("Arthrosis of first carpometacarpal joint","Diseases of the musculoskeletal system and connective tissue","M18");
ICD10.put("Polyarteritis nodosa","Diseases of the musculoskeletal system and connective tissue","M30.0");
ICD10.put("Systemic lupus erythematosus","Diseases of the musculoskeletal system and connective tissue","M32");
ICD10.put("Dermatopolymyositis","Diseases of the musculoskeletal system and connective tissue","M33");
ICD10.put("Systemic sclerosis","Diseases of the musculoskeletal system and connective tissue","M34");
ICD10.put("Postural pyphosis","Diseases of the musculoskeletal system and connective tissue","M40.0");
ICD10.put("Flatback syndrome","Diseases of the musculoskeletal system and connective tissue","M40.3");
ICD10.put("Scoliosis","Diseases of the musculoskeletal system and connective tissue","M41");
ICD10.put("Spinal osteochondrosis","Diseases of the musculoskeletal system and connective tissue","M42");
ICD10.put("Ankylosing spondylitis","Diseases of the musculoskeletal system and connective tissue","M45");
ICD10.put("Spondylosis","Diseases of the musculoskeletal system and connective tissue","M47");
ICD10.put("Cervical disc disorder","Diseases of the musculoskeletal system and connective tissue","M50");
ICD10.put("Dorsalgia","Diseases of the musculoskeletal system and connective tissue","M54");
ICD10.put("Myositis","Diseases of the musculoskeletal system and connective tissue","M60");
ICD10.put("Diastasis of muscle","Diseases of the musculoskeletal system and connective tissue","M62.0");
ICD10.put("Ischaemic infarction of muscle","Diseases of the musculoskeletal system and connective tissue","M62.2");
ICD10.put("Immobility syndrome(paraplegic)","Diseases of the musculoskeletal system and connective tissue","M62.3");
ICD10.put("Synovitis and tenosynovitis","Diseases of the musculoskeletal system and connective tissue","M65");
ICD10.put("Spontaneous rupture of synovium and tendon","Diseases of the musculoskeletal system and connective tissue","M66");
ICD10.put("Medical epicondylitis","Diseases of the musculoskeletal system and connective tissue","M77.0");
ICD10.put("Lateral epicondylitis","Diseases of the musculoskeletal system and connective tissue","M77.1");
ICD10.put("Periarthritis of wrist","Diseases of the musculoskeletal system and connective tissue","M77.2");
ICD10.put("Calcaneal spur","Diseases of the musculoskeletal system and connective tissue","M77.3");
ICD10.put("Metatarsalgia","Diseases of the musculoskeletal system and connective tissue","M77.4");
ICD10.put("Rheumatism","Diseases of the musculoskeletal system and connective tissue","M79.0");
ICD10.put("Myalgia","Diseases of the musculoskeletal system and connective tissue","M79.1");
ICD10.put("Neuralgia and neuritis","Diseases of the musculoskeletal system and connective tissue","M79.2");
ICD10.put("Panniculitis","Diseases of the musculoskeletal system and connective tissue","M79.3");
ICD10.put("Hypertrophy of fat pad","Diseases of the musculoskeletal system and connective tissue","M79.4");
ICD10.put("Fibromyalgia","Diseases of the musculoskeletal system and connective tissue","M79.7");
ICD10.put("Osteoporosis with pathological fracture","Diseases of the musculoskeletal system and connective tissue","M80");
ICD10.put("Osteoporosis without pathological fracture","Diseases of the musculoskeletal system and connective tissue","M81");
ICD10.put("Adult osteomalacia","Diseases of the musculoskeletal system and connective tissue","M83");
ICD10.put("Disorders of continuity of bone","Diseases of the musculoskeletal system and connective tissue","M84");
ICD10.put("Osteomyelitis","Diseases of the musculoskeletal system and connective tissue","M86");
ICD10.put("Osteonecrosis","Diseases of the musculoskeletal system and connective tissue","M87");
ICD10.put("Paget disease of bone[osteitis deformans]","Diseases of the musculoskeletal system and connective tissue","M88");
ICD10.put("Juvenile osteochondrosis of hip and pelvis","Diseases of the musculoskeletal system and connective tissue","M91");
ICD10.put("Acute nephritic syndrome","Diseases of the genitourinary system","N00");
ICD10.put("Rapidly progressive nephritic syndrome","Diseases of the genitourinary system","N01");
ICD10.put("Recurrent and persistent haematuria","Diseases of the genitourinary system","N02");
ICD10.put("Chronic nephritic syndrome","Diseases of the genitourinary system","N03");
ICD10.put("Nephrotic syndrome","Diseases of the genitourinary system","N04");
ICD10.put("Acute tubulo-interstitial nephritis","Diseases of the genitourinary system","N10");
ICD10.put("Chronic tubulo-interstitial nephritis","Diseases of the genitourinary system","N10");
ICD10.put("Obstructive and reflux uropathy","Diseases of the genitourinary system","N13");
ICD10.put("Analgesic nephropathy","Diseases of the genitourinary system","N14.0");
ICD10.put("Toxic nephropathy","Diseases of the genitourinary system","N14.4");
ICD10.put("Acute renal failure","Diseases of the genitourinary system","N17");
ICD10.put("Chronic kidney disease","Diseases of the genitourinary system","N18");
ICD10.put("Calculus of kidney","Diseases of the genitourinary system","N20.0");
ICD10.put("Calculus of ureter","Diseases of the genitourinary system","N20.1");
ICD10.put("Calculus in bladder","Diseases of the genitourinary system","N21.0");
ICD10.put("Calculus in urethra","Diseases of the genitourinary system","N21.1");
ICD10.put("Cystitis","Diseases of the genitourinary system","N30");
ICD10.put("Neuromuscular dysfunction of bladder","Diseases of the genitourinary system","N31");
ICD10.put("Urethritis and urethral syndrome","Diseases of the genitourinary system","N34");
ICD10.put("Urethral stricture","Diseases of the genitourinary system","N35");
ICD10.put("Hyperplasia of prostrate","Diseases of the genitourinary system","N40");
ICD10.put("Acute prostatitis","Diseases of the genitourinary system","N41.0");
ICD10.put("Chronic prostatitis","Diseases of the genitourinary system","N41.1");
ICD10.put("Abscess of prostate","Diseases of the genitourinary system","N41.2");
ICD10.put("Prostatocystitis","Diseases of the genitourinary system","N41.3");
ICD10.put("Torsion of testis","Diseases of the genitourinary system","N44");
ICD10.put("Orchitis and epididymitis","Diseases of the genitourinary system","N45");
ICD10.put("Male infertility","Diseases of the genitourinary system","N46");
ICD10.put("Redundant prepuce","Diseases of the genitourinary system","N47");
ICD10.put("Benign mammary dysplasia","Diseases of the genitourinary system","N60");
ICD10.put("Inflammatory disorders of breast","Diseases of the genitourinary system","N61");
ICD10.put("Hypertrophy of breast","Diseases of the genitourinary system","N62");
ICD10.put("Salpingitis and oophoritis","Diseases of the genitourinary system","N70");
ICD10.put("Inflammatory disease of uterus","Diseases of the genitourinary system","N71");
ICD10.put("Inflammatory disease of cervix uteri","Diseases of the genitourinary system","N72");
ICD10.put("Disease of Barholin gland","Diseases of the genitourinary system","N75");
ICD10.put("Endometriosis","Diseases of the genitourinary system","N80");
ICD10.put("Female genital prolapse","Diseases of the genitourinary system","N81");
ICD10.put("Erois and ectropion of cervix uteri","Diseases of the genitourinary system","N86");
ICD10.put("Dysplasia of cervix uteri","Diseases of the genitourinary system","N87");
	}
	

	
public Table<String, String, String> searchText(){
for (String key : ICD10.rowKeySet()) {
	 if(StringUtils.getLevenshteinDistance(ICD10.row(key).toString().toLowerCase(),key.toLowerCase()) <= (2)){
      if(ICD10.row(key).toString().toLowerCase().contains(key.toLowerCase())){
    	   Map<String, String> tmp = ICD10.row(key);
    	   for (java.util.Map.Entry<String, String> pair : tmp.entrySet()) {
    	        diseases.put(key,pair.getKey(),pair.getValue());
    	    }
    }
 
      }

}
return diseases;
}


}




	
	

